export type DnsTag = "iran" | "global" | "privacy" | "gaming" | "ads" | "family";

export interface DnsProvider {
  id: string;
  name: string;
  nameFa: string;
  primary: string;
  secondary: string;
  tags: DnsTag[];
  original?: boolean;
  blurb: string;
  blurbFa: string;
}

export const DNS_PROVIDERS: DnsProvider[] = [
  {
    id: "403",
    name: "403",
    nameFa: "۴۰۳",
    primary: "185.55.226.26",
    secondary: "185.55.225.25",
    tags: ["iran"],
    original: true,
    blurb: "Original toolkit profile for 403.",
    blurbFa: "پروفایل اصلی تولکیت برای ۴۰۳.",
  },
  {
    id: "shecan",
    name: "Shecan",
    nameFa: "شکن",
    primary: "178.22.122.100",
    secondary: "185.51.200.2",
    tags: ["iran"],
    original: true,
    blurb: "Anti-sanction DNS for developers and general browsing.",
    blurbFa: "دی‌ان‌اس رفع تحریم برای توسعه و وب‌گردی.",
  },
  {
    id: "electro",
    name: "Electro",
    nameFa: "الکترو",
    primary: "78.157.42.100",
    secondary: "78.157.42.101",
    tags: ["iran", "gaming"],
    original: true,
    blurb: "Gaming-friendly anti-sanction resolver.",
    blurbFa: "رفع تحریم مناسب بازی.",
  },
  {
    id: "google",
    name: "Google DNS",
    nameFa: "گوگل",
    primary: "8.8.8.8",
    secondary: "8.8.4.4",
    tags: ["global"],
    original: true,
    blurb: "Public Google resolvers.",
    blurbFa: "دی‌ان‌اس عمومی گوگل.",
  },
  {
    id: "cloudflare",
    name: "Cloudflare",
    nameFa: "کلادفلر",
    primary: "1.1.1.1",
    secondary: "1.0.0.1",
    tags: ["global", "privacy"],
    original: true,
    blurb: "Fast privacy-oriented anycast DNS.",
    blurbFa: "دی‌ان‌اس سریع و حریم‌خصوصی.",
  },
  {
    id: "opendns",
    name: "OpenDNS",
    nameFa: "اوپن‌دی‌ان‌اس",
    primary: "208.67.222.222",
    secondary: "208.67.220.220",
    tags: ["global", "family"],
    original: true,
    blurb: "Cisco OpenDNS with optional filtering.",
    blurbFa: "اوپن‌دی‌ان‌اس سیسکو با فیلتر اختیاری.",
  },
  {
    id: "quad9",
    name: "Quad9",
    nameFa: "کواد۹",
    primary: "9.9.9.9",
    secondary: "149.112.112.112",
    tags: ["global", "privacy"],
    original: true,
    blurb: "Security-blocking recursive DNS.",
    blurbFa: "دی‌ان‌اس امنیتی با مسدودسازی بدافزار.",
  },
  {
    id: "comodo",
    name: "Comodo",
    nameFa: "کومودو",
    primary: "8.26.56.26",
    secondary: "8.20.247.20",
    tags: ["global", "privacy"],
    original: true,
    blurb: "Comodo Secure DNS.",
    blurbFa: "دی‌ان‌اس امن کومودو.",
  },
  {
    id: "cleanbrowsing",
    name: "CleanBrowsing",
    nameFa: "کلین‌براوزینگ",
    primary: "185.228.168.9",
    secondary: "185.228.169.9",
    tags: ["global", "family"],
    original: true,
    blurb: "Family-safe filtered DNS.",
    blurbFa: "دی‌ان‌اس خانواده با فیلتر محتوا.",
  },
  {
    id: "adguard",
    name: "AdGuard",
    nameFa: "ادگارد",
    primary: "94.140.14.14",
    secondary: "94.140.15.15",
    tags: ["global", "ads", "privacy"],
    original: true,
    blurb: "Blocks ads and trackers at DNS level.",
    blurbFa: "مسدودسازی تبلیغ و ترکر در لایه DNS.",
  },
  {
    id: "yandex",
    name: "Yandex",
    nameFa: "یاندکس",
    primary: "77.88.8.8",
    secondary: "77.88.8.1",
    tags: ["global"],
    original: true,
    blurb: "Yandex public DNS.",
    blurbFa: "دی‌ان‌اس عمومی یاندکس.",
  },
  {
    id: "403-online",
    name: "403 Online",
    nameFa: "۴۰۳ آنلاین",
    primary: "10.202.10.202",
    secondary: "10.202.10.102",
    tags: ["iran"],
    blurb: "Newer 403.online anycast pair.",
    blurbFa: "جفت جدید ۴۰۳ آنلاین.",
  },
  {
    id: "radar",
    name: "Radar Game",
    nameFa: "رادار گیم",
    primary: "10.202.10.10",
    secondary: "10.202.10.11",
    tags: ["iran", "gaming"],
    blurb: "Low-latency gaming DNS inside Iran.",
    blurbFa: "دی‌ان‌اس گیم با پینگ پایین داخل ایران.",
  },
  {
    id: "shelter",
    name: "Shelter",
    nameFa: "شلتر",
    primary: "185.86.136.241",
    secondary: "185.86.136.242",
    tags: ["iran"],
    blurb: "Developer anti-sanction resolver.",
    blurbFa: "رفع تحریم مخصوص توسعه.",
  },
  {
    id: "level15",
    name: "Level 15",
    nameFa: "لول ۱۵",
    primary: "185.105.238.167",
    secondary: "185.105.239.167",
    tags: ["iran", "gaming"],
    blurb: "Gaming / anti-sanction pair.",
    blurbFa: "گیم و رفع تحریم.",
  },
  {
    id: "vanilla",
    name: "Vanilla",
    nameFa: "وانیل",
    primary: "10.202.10.100",
    secondary: "10.202.10.101",
    tags: ["iran"],
    blurb: "Vanilla anti-sanction DNS.",
    blurbFa: "دی‌ان‌اس رفع تحریم وانیل.",
  },
  {
    id: "level3",
    name: "Level3",
    nameFa: "لول۳",
    primary: "4.2.2.4",
    secondary: "4.2.2.1",
    tags: ["global"],
    blurb: "Classic Level3 resolvers used in ping tests.",
    blurbFa: "رزالوهای کلاسیک لول۳ برای تست پینگ.",
  },
  {
    id: "controld",
    name: "Control D",
    nameFa: "کنترل‌دی",
    primary: "76.76.2.0",
    secondary: "76.76.10.0",
    tags: ["global", "privacy", "ads"],
    blurb: "Customizable filtered DNS.",
    blurbFa: "دی‌ان‌اس قابل‌تنظیم با فیلتر.",
  },
  {
    id: "dnssb",
    name: "DNS.SB",
    nameFa: "DNS.SB",
    primary: "185.222.222.222",
    secondary: "45.11.45.11",
    tags: ["global", "privacy"],
    blurb: "No-log public DNS.",
    blurbFa: "دی‌ان‌اس عمومی بدون لاگ.",
  },
];

export const DEFAULT_ADAPTERS = [
  { name: "Ethernet", admin: "Enabled" as const, state: "Connected" as const },
  { name: "Wi-Fi", admin: "Enabled" as const, state: "Connected" as const },
  { name: "Ethernet 2", admin: "Enabled" as const, state: "Disconnected" as const },
  { name: "vEthernet (WSL)", admin: "Enabled" as const, state: "Connected" as const },
];

export function providerById(id: string | null | undefined) {
  if (!id) return undefined;
  return DNS_PROVIDERS.find((p) => p.id === id);
}
